### ISSUE TITLE
Fehler in Gedicht "Öbere" in Notizbuch 1979-82

### ISSUE THREAD

**Issue by sschuepbach** [nie-ine/raeber-website#112]
Beim Aufrufen des Gedichtes Öbere (Notizbuch 1979-82) wird ein Fehler geworfen, der offenbar im Steckbrief auftritt. Ansonsten ist mir der Fehler bei keinem Gedicht begegnet, allerdings habe ich auch nicht systematisch geprüft.

```
ERROR TypeError: Cannot read property 'push' of undefined
    at SafeSubscriber.eval [as _next] (http://localhost:5555/app/fassung/fassung-steckbrief/fassung-steckbrief-fassung.component.js:29:35)
    at SafeSubscriber.__tryOrUnsub (http://localhost:5555/node_modules/.tmp/Rx.min.js?1509135582393:1:337028)
    at SafeSubscriber.next (http://localhost:5555/node_modules/.tmp/Rx.min.js?1509135582393:1:336049)
    at Subscriber._next (http://localhost:5555/node_modules/.tmp/Rx.min.js?1509135582393:1:334604)
    at Subscriber.next (http://localhost:5555/node_modules/.tmp/Rx.min.js?1509135582393:1:334222)
    at MapSubscriber._next (http://localhost:5555/node_modules/.tmp/Rx.min.js?1509135582393:1:338775)
    at MapSubscriber.Subscriber.next (http://localhost:5555/node_modules/.tmp/Rx.min.js?1509135582393:1:334222)
    at XMLHttpRequest.onLoad (http://localhost:5555/node_modules/@angular/http/bundles/http.umd.js:1259:38)
    at ZoneDelegate.invokeTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:424:31)
    at Object.onInvokeTask (http://localhost:5555/node_modules/@angular/core/bundles/core.umd.js:3913:33)
    at ____________________Elapsed_148_ms__At__Fri_Oct_27_2017_22_40_21_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/long-stack-trace-zone.js?1509135582393:109:22)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:300:29)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Zone.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:235:43)
    at Zone.scheduleEventTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:261:25)
    at zoneAwareAddListener (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:1279:14)
    at XMLHttpRequest.proto.(anonymous function) [as addEventListener] (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:1426:20)
    at ____________________Elapsed_319_ms__At__Fri_Oct_27_2017_22_40_21_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/long-stack-trace-zone.js?1509135582393:109:22)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:300:29)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Zone.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:235:43)
    at Zone.scheduleEventTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:261:25)
    at zoneAwareAddListener (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:1279:14)
    at XMLHttpRequest.proto.(anonymous function) [as addEventListener] (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:1426:20)
    at ____________________Elapsed_3_ms__At__Fri_Oct_27_2017_22_40_21_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/long-stack-trace-zone.js?1509135582393:109:22)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:300:29)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Zone.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:235:43)
    at Zone.scheduleMicroTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:255:25)
    at scheduleResolveOrReject (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:816:14)
    at resolvePromise (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:765:21)
    at ____________________Elapsed_0_ms__At__Fri_Oct_27_2017_22_40_21_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/long-stack-trace-zone.js?1509135582393:109:22)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:300:29)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Zone.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:235:43)
    at Zone.scheduleMicroTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:255:25)
    at scheduleResolveOrReject (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:816:14)
    at resolvePromise (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:765:21)
    at ____________________Elapsed_0_ms__At__Fri_Oct_27_2017_22_40_21_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/long-stack-trace-zone.js?1509135582393:109:22)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:300:29)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Zone.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:235:43)
    at Zone.scheduleMicroTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:255:25)
    at scheduleResolveOrReject (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:816:14)
    at resolvePromise (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:765:21)
    at ____________________Elapsed_0_ms__At__Fri_Oct_27_2017_22_40_21_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/long-stack-trace-zone.js?1509135582393:109:22)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:300:29)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Zone.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:235:43)
    at Zone.scheduleMicroTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:255:25)
    at scheduleResolveOrReject (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:816:14)
    at resolvePromise (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:765:21)
    at ____________________Elapsed_2_ms__At__Fri_Oct_27_2017_22_40_21_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/long-stack-trace-zone.js?1509135582393:109:22)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:300:29)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Zone.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:235:43)
    at Zone.scheduleMicroTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:255:25)
    at scheduleResolveOrReject (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:816:14)
    at resolvePromise (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:765:21)
    at ____________________Elapsed_12_ms__At__Fri_Oct_27_2017_22_40_21_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/long-stack-trace-zone.js?1509135582393:109:22)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:300:29)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Zone.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:235:43)
    at Zone.scheduleMicroTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:255:25)
    at scheduleResolveOrReject (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:816:14)
    at ZoneAwarePromise.then (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:905:17)
    at ____________________Elapsed_5_ms__At__Fri_Oct_27_2017_22_40_21_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/long-stack-trace-zone.js?1509135582393:109:22)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:300:29)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Zone.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:235:43)
    at Zone.scheduleMicroTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:255:25)
    at scheduleResolveOrReject (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:816:14)
    at ZoneAwarePromise.then (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:905:17)
    at ____________________Elapsed_1218467_ms__At__Fri_Oct_27_2017_22_20_02_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/long-stack-trace-zone.js?1509135582393:109:22)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Object.onScheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:300:29)
    at ZoneDelegate.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:404:51)
    at Zone.scheduleTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:235:43)
    at Zone.scheduleEventTask (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:261:25)
    at zoneAwareAddListener (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:1279:14)
    at HTMLAnchorElement.proto.(anonymous function) [as addEventListener] (http://localhost:5555/node_modules/zone.js/dist/zone.js?1509135582393:1426:20)
```

**Comment by rfbaumgartner** [comment]
Das sollte der Link zum Bezugstext sein. 

Bei Gelegenheit müsste man prüfen, ob der Fehler inzwischen behoben ist.

**Comment by rfbaumgartner** [comment]
Trat bei mir heute nicht mehr auf
