### ISSUE TITLE
Error: Unexpected value 'undefined' imported by the module 'KonvolutModule'

### ISSUE THREAD

**Issue by afa-unibas** [nie-ine/raeber-website#52]
Building and running master locally on Ubuntu 16.04 gives me the following error in the browser console (hanging the load of the start site). This is both with `docker-compose` and `npm start`:
Any ideas? :fire_engine:

```
localhost/:65 Error: Unexpected value 'undefined' imported by the module 'KonvolutModule'
    at syntaxError (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at eval (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:15588:40)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:15565:49)
    at CompileMetadataResolver.getNgModuleSummary (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:15507:52)
    at eval (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:15580:72)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:15565:49)
    at CompileMetadataResolver.getNgModuleSummary (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:15507:52)
    at eval (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:15580:72) Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues
(anonymous) @ localhost/:65
```

**Comment by afa-unibas** [comment]
:hammer_and_wrench:  around it with the 3 following commands:

``` 
npm install @angular/material@2.0.0-beta.11
mat-switcher -p ./tsconfig.json  
npm install @angular/material@2.0.0-beta.12
```
